config/routes.rb
Rails.application.routes.draw do
  resources :users, only: %i(edit update destroy)

  # Root
  root to: 'visitors#index'

  # Sign-in and authentication.
  get '/signin'                 => 'sessions#new',     as: :signin
  get '/signout'                => 'sessions#destroy', as: :signout
  get '/auth/facebook/callback' => 'sessions#create',  as: :facebook_callback
  get '/auth/failure'           => 'sessions#failure'

  # Connecting to google.
  get '/auth/google/redirect'   => 'google_oauth#redirect',  as: :google_redirect
  get '/auth/google/callback'   => 'google_oauth#callback',  as: :google_callback
  get '/auth/google/revoke'     => 'google_oauth#revoke',    as: :google_revoke
  get '/calendars'              => 'google_oauth#calendars', as: :calendars

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :tasks do
        get 'steps', on: :member
      end
    end
  end
end

app/views/layouts/_messages.slim
- flash.each do |type, contents|
  div class="alert alert-#{type.to_s == 'notice' ? 'success' : 'danger'}"
    button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×

    - if contents.is_a?(String)
      = content_tag :div, contents, id: "flash_#{type}"

    - elsif contents.is_a?(Hash)
      // Ignore hashes for now.
      / - contents.each do |name, problems|
      /   - problems.each do |problem|
      /     = "#{name} #{problem}"

    - elsif contents.is_a?(Array)
      - contents.each do |msg|
        = msg

app/views/layouts/_nav.slim
- if signed_in?
  li= link_to 'Sign out', signout_path
  li= current_user.name
  li= link_to 'Tasks', root_path
  - if current_user.access_token.nil?
    li= link_to 'Connect GCal', 'auth/google/redirect'
  - else
    li= link_to 'Calendars', calendars_path
    li= link_to 'Revoke', google_revoke_path
- else
  li= link_to 'Sign in', signin_path

app/views/layouts/application.html.slim
doctype html
html

  head
    title= yield(:title) || 'Feito'
    meta name='description' content="#{yield(:description) || 'Feito'}"
    = favicon_link_tag       'favicon.png'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body.container
    = render 'layouts/nav'
    = render 'layouts/messages'
    = yield